### ISSUE TITLE
Close button not active when mouse is at the very corner of screen

### ISSUE THREAD

**Issue by rokups** [psifidotos/applet-window-buttons#11]
When window is maximized, close button in window titlebar is placed in such a way that moving mouse to very corner where button is still hovers that button. As a result we can rapidly flick the mouse to the direction of that corner and click without aiming in order to close that window. This is not the case with this applet. Be great if mouse positioned like in screenshot would be able to click on the button.
![image](https://user-images.githubusercontent.com/19151258/48148362-383f3780-e2c2-11e8-9b51-17c209cf6612.png)

**Comment by psifidotos** [comment]
has been just fixed in master. The behavior you are requesting in called Fitt's Law.
Make sure to set the left margin to 0px.

**Comment by rokups** [comment]
Thank you :)

> The behavior you are requesting in called Fitt's Law.

TIL :)

**Comment by rokups** [comment]
Strange thing. Now button is active when mouse is at the very corner, but clicking does nothing. Button does change color reacting to clicking but window does not close. Clicking bit towards button center works though.

Initially i thought this was issue with my latte layout as opening layouts dialog warned about broken layout, but now that i sorted this issue out problem still persists.

**Comment by psifidotos** [comment]
show me please a video and your settings window

**Comment by psifidotos** [comment]
no need... I reproduced....

**Comment by rokups** [comment]
Latest commit fixes closing, but when mouse is at very corner button no longer displays hovering effect.

**Comment by psifidotos** [comment]
are you using Latte?

**Comment by rokups** [comment]
I am

**Comment by psifidotos** [comment]
> I am

just fixed in git version with: https://phabricator.kde.org/R878:5c82996dfa8d4a344631e7765d1184366ddc6fcc

and also for upcoming v0.8.3

**Comment by bidinou** [comment]
Hi ! Maybe I'm mistaken : I've built the git / master versionas of today and I still have the same issue :  
whenever my mouse is at the very top of the screen (and thus, the top-right corner), clicking on the applet makes it "blink" but doesn't actually close the window. It does when clicking on the right though.
Screenshot (the "X" should turn red with the mouse hover) : https://ibb.co/k0eY3V

Thanks again ! :-)

**Comment by psifidotos** [comment]
Have you set the right margin to 0px.?

**Comment by psifidotos** [comment]
You are using the Latte plasmoid in the panel, only way this could work is:

1. Show activation line in reverse, you can do that from Appearance
2. After 1 enable from Tweaks - > Shrink thickness margins to minimum

**Comment by bidinou** [comment]
> Have you set the right margin to 0px.? 
Yep !

> Show activation line in reverse, you can do that from Appearance
Oh, that fixes it, I wouldn't have guessed that !

Thanks again, and sorry for adding noise to this bugreport !!
